id = "mix"
name = "MIX"
version = "0.0.1"
schema_version = 1
authors = ["Varomix"]
description = "MIX language support for Zed: Tree-sitter highlighting and mix-lsp integration."
repository = "https://github.com/varomix/mix-lang"

[grammars.mix]
repository = "file:///Users/varomix/dev/MIX_DEV/mix_lang/editors/zed-mix/tree-sitter-mix"
rev = "5aaab235a2e3cd1cab077095e809a20131f0d4b6"

[language_servers.mix-lsp]
name = "mix-lsp"
languages = ["MIX"]

[language_servers.mix-lsp.language_ids]
"MIX" = "mix"
