id = "mix"
name = "MIX"
version = "0.0.1"
schema_version = 1
authors = ["Varomix"]
description = "MIX language support for Zed: Tree-sitter highlighting and mix-lsp integration."
repository = "https://github.com/varomix/mix-lang"
languages = ["languages/mix"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.mix]
repository = "file:///Users/varomix/dev/MIX_DEV/mix_lang/editors/zed-mix/tree-sitter-mix"
rev = "920b25a058fd1da8439b10d91fe5b1a0a15c33b5"

[language_servers.mix-lsp]
language = "MIX"

[language_servers.mix-lsp.language_ids]
"MIX" = "mix"
